sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_ea0491910a78_key -iv $encrypted_ea0491910a78_iv -in multi-k8s-298021-5dabb4ae4563.json.enc -out multi-k8s-298021-5dabb4ae4563.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null - # get the google sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # load in some shell configurations
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-298021-5dabb4ae4563.json # like iAM on aws
  - gcloud config set project multi-k8s-298021
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t betauser001/react-test -f ./client/Dockerfile.dev ./client
scripts:
  - docker run -e CI=true betauser001/react-test npm test
